[package]
name = "serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compact_str = { version = "0.5", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
